### PR TITLE
changes applied for inserting a footer at the bottom of each pdf

### PR DESCRIPTION
**Pull request by PrakritiShetty**
# Description

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

## Development & Testing Configuration 

* react version:
* react-router version:
* SCSS version:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have read and agree with [Code of Conduct](https://github.com/DunoLabs/invoicetor-landing/blob/main/CODE_OF_CONDUCT.md)

- [x] I have read and agree with [Contributing](https://github.com/dunolabs/invoicetor-landing/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by wh0sumit** [comment]
Is it possible for you to share multipage Invoice PDF screenshots or video recordings??

**Comment by PrakritiShetty** [comment]
Sure! I made an invoice such that it spanned to two pages, and that's the watermark on the bottom left.

image
image

**Comment by PrakritiShetty** [comment]
Hi @wh0sumit do the screenshots look okay?

**Comment by PrakritiShetty** [comment]
Hi @wh0sumit and @yashsehgal, could y'all please check if this is fine? Actually I'm trying out hacktoberfest, and I really want to be in the 40,000 completing first, hence the slight urgency!

**Comment by PrakritiShetty** [comment]
Hi @wh0sumit and @yashsehgal could y'all reply to this thread please?

**Comment by wh0sumit** [comment]
due to our busy schedules lately, we have not responded to your PR. We are reviewing it now and will let you know shortly about it!

**Comment by wh0sumit** [comment]
we're not able to review it properly because of some conflicts. Could you please take a pull request and raise the PR again!

**Comment by PrakritiShetty** [comment]
Done! Could you please check the new PR (#49)?

**Pull request closed without merging**
